apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: dev
spec:
  containers:
  - name: app-container
    image: nginx
    resources:
      requests:
        cpu: "1"      # This pod asks for 1 CPU
        memory: "2Gi" # This pod asks for 2GB memory
