apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort  # This makes the service a NodePort service
  selector:
    app: my-app  # This selects the pods with label app=my-app
  ports:
    - protocol: TCP
      port: 80        # Port on the service
      targetPort: 80   # Port on the pod
      nodePort: 30001  # The external port on each node (choose a value within the 30000-32767 range)
